spring:
  application:
    name: ckb-explorer-web
  threads:
    virtual:
      enabled: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: rivtower
#    password: rivtower
#    virtual-host: /
  datasource:
    dynamic:
      primary: postgres  # 默认数据源（PostgreSQL）
      strict: false      # 非严格模式，允许未指定数据源时使用默认数据源
      datasource:
        # PostgreSQL 数据源配置
        postgres:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.120.129:30153/ckb-rich-indexer
          username: postgres
          password: 123456
        # RisingWave 数据源配置（兼容PostgreSQL协议）
        risingwave:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.120.129:30456/dev  # RisingWave默认端口4566，数据库名dev
          username: root  # RisingWave默认用户名
          password: ""    # RisingWave默认无密码
  data:
    redis:
      #host: localhost
      host: 192.168.10.143
      #port: 6379
      port: 6350
      database: 4
        # lettuce:
        #   pool:
          # 虚拟线程下建议关闭连接池（每个请求短平快）
          #     max-active: 200
      #password: abcdefg
      redisson:
        config: |
          singleServerConfig:
            #address: redis://localhost:6379
            #password: abcdefg
            address: redis://192.168.10.143:6350
            database: 4
            idleConnectionTimeout: 10000
            connectTimeout: 10000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
            subscriptionsPerConnection: 5
            clientName: ckb-explorer-web
            # 降低连接池
            connectionMinimumIdleSize: 4
            connectionPoolSize: 16
            dnsMonitoringInterval: 5000
            codec: !<org.redisson.codec.JsonJacksonCodec> {}
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog.yml
    database-change-log-lock-table: liquibase-lock
    database-change-log-table: liquibase-changelog
logging:
  level:
    com.ckb.explorer.mapper: DEBUG
    com.baomidou: DEBUG
ckb:
  nodeUrl: https://testnet.ckb.dev
  netWork: 2 # 1:mainnet 2:testnet
  default-hash-prefix: 0x
  default-with-prefix-hash-length: 66
  typeIdCodeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944"
statistic:
  averageBlockTimeInterval: 100
  hashRateStatisticalInterval: 100
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
script:
  lockScripts:
    - name: "SECP256K1/blake160"
      codeHash: "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37",
          index: 0,
          depType: "depGroup"
        }
      ]
    - name: "SECP256k1/Multisig(@5c5069eb)"
      codeHash: "0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37",
          index: 1,
          depType: "depGroup"
        }
      ]
    - name: "SECP256k1/Multisig(@36c971b8)"
      codeHash: "0x36c971b8d41fbd94aabca77dc75e826729ac98447b46f91e00796155dddb0d29"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0x2eefdeb21f3a3edf697c28a52601b4419806ed60bb427420455cc29a090b26d5",
          index: 0,
          depType: "depGroup"
        }
      ]
    - name: "iCKB Logic"
      codeHash: "0x2a8100ab5990fa055ab1b50891702e1e895c7bd1df6322cd725c1a6115873bd3"
      hashType: "data1"
    - name: "AnyoneCanPay"
      codeHash: "0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xec26b0f85ed839ece5f11c4c4e837ec359f5adc4420410f6453b1f6b60fb96a6",
          index: 0,
          depType: "depGroup"
        }
      ]
    - name: "CHEQUE"
      codeHash: "0x60d5f39efce409c587cb9ea359cefdead650ca128f0bd9cb3855348f98c70d5b"
      hashType: "type"
    - name: "JoyId"
      codeHash: "0xd23761b364210735c19c60561d213fb3beae2fd6172743719eff6920e020baac"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0x4a596d31dc35e88fb1591debbf680b04a44b4a434e3a94453c21ea8950ffb4d9",
          index: 0,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0x1c9fc299ba0570d077b4d7fb9acff1ccc0de69d369942d82678bae937c44ec30"
          }
        },
        {
          txHash: "0x4a596d31dc35e88fb1591debbf680b04a44b4a434e3a94453c21ea8950ffb4d9",
          index: 1,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0x27f0d3ccdc2fcd52ae31fbacad5f86b97bc147d7093e4807cd6e3d21c1fe6841"
          }
        },
        {
          txHash: "0xf2c9dbfe7438a8c622558da8fa912d36755271ea469d3a25cb8d3373d35c8638",
          index: 1,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0x0ac15fe5b2d059ec39de03f2d3159d5463abb918a1a07a9fa00d2b9c61d89ef3"
          }
        },
        {
          txHash: "0x95ecf9b41701b45d431657a67bbfa3f07ef7ceb53bf87097f3674e1a4a19ce62",
          index: 1,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0xc7bafc5550ccad7cea32c27764f5df6aca4de547da65e3e67fa08477a1af7f5e"
          }
        },
        {
          txHash: "0x8b3255491f3c4dcc1cfca33d5c6bcaec5409efe4bbda243900f9580c47e0242e",
          index: 1,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0x71decef9ca8725e64ec99a5521790d16b8d5daadb4989b45dd6ab51806a8c0e4"
          }
        }
      ]
    - name: "OMNI Lock V2"
      codeHash: "0xf329effd1c475a2978453c8600e1eaf0bc2087ee093c3ee64cc96ec6847752cb"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37",
          index: 0,
          depType: "depGroup"
        },
        {
          txHash: "0xec18bf0d857c981c3d1f4e17999b9b90c484b303378e94de1a57b0872f5d4602",
          index: 0,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0x761f51fc9cd6a504c32c6ae64b3746594d1af27629b427c5ccf6c9a725a89144"
          }
        }
      ]
    - name: "OMNI Lock V1"
      codeHash: "0x79f90bb5e892d80dd213439eeab551120eb417678824f282b4ffb5f21bad2e1e"
      hashType: "type"
    - name: "PW Lock"
      codeHash: "0x58c5f491aba6d61678b7cf7edf4910b1f5e00ec0cde2f42e0abb4fd9aff25a63"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37",
          index: 0,
          depType: "depGroup"
        },
        {
          txHash: "0x57a62003daeab9d54aa29b944fc3b451213a5ebdf2e232216a3cfed0dde61b38",
          index: 0,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0xf6d90bfe3041d0fd7e01c45770241697f5f837974bd6ae1672a7ec0f9f523268"
          }
        }
      ]
    - name: "Nostr"
      codeHash: "0x6ae5ee0cb887b2df5a9a18137315b9bdc55be8d52637b2de0624092d5f0c91d5"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xa2a434dcdbe280b9ed75bb7d6c7d68186a842456aba0fc506657dc5ed7c01d68",
          index: 0,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0x8dc56c6f35f0c535e23ded1629b1f20535477a1b43e59f14617d11e32c50e0aa"
          }
        }
      ]
    - name: "RgbppLock"
      codeHash: "0x61ca7a4796a4eb19ca4f0d065cb9b10ddcf002f10f7cbb810c706cb6bb5c3248"
      hashType: "type"
    - name: "BtcTimeLock"
      codeHash: "0x00cdf8fab0f8ac638758ebf5ea5e4052b1d71e8a77b9f43139718621f6849326"
      hashType: "type"
    - name: "AlwaysSuccess"
      codeHash: "0x3b521cc4b552f109d092d8cc468a8048acb53c5952dbe769d2b2f9cf6e47f7f1"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0xb4f171c9c9caf7401f54a8e56225ae21d95032150a87a4678eac3f66a3137b93",
          index: 0,
          depType: "code"
        }
      ]
    - name: "InputTypeProxyLock"
      codeHash: "0x5123908965c711b0ffd8aec642f1ede329649bda1ebdca6bd24124d3796f768a"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0xb4f171c9c9caf7401f54a8e56225ae21d95032150a87a4678eac3f66a3137b93",
          index: 1,
          depType: "code"
        }
      ]
    - name: "OutputTypeProxyLock"
      codeHash: "0x2df53b592db3ae3685b7787adcfef0332a611edb83ca3feca435809964c3aff2"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0xb4f171c9c9caf7401f54a8e56225ae21d95032150a87a4678eac3f66a3137b93",
          index: 2,
          depType: "code"
        }
      ]
    - name: "LockProxyLock"
      codeHash: "0x5d41e32e224c15f152b7e6529100ebeac83b162f5f692a5365774dad2c1a1d02"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0xb4f171c9c9caf7401f54a8e56225ae21d95032150a87a4678eac3f66a3137b93",
          index: 3,
          depType: "code"
        }
      ]
    - name: "Single Use Lock"
      codeHash: "0x8290467a512e5b9a6b816469b0edabba1f4ac474e28ffdd604c2a7c76446bbaf"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0xb4f171c9c9caf7401f54a8e56225ae21d95032150a87a4678eac3f66a3137b93",
          index: 4,
          depType: "code"
        }
      ]
    - name: "TypeBurnLock"
      codeHash: "0xff78bae0abf17d7a404c0be0f9ad9c9185b3f88dcc60403453d5ba8e1f22f53a"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0xb4f171c9c9caf7401f54a8e56225ae21d95032150a87a4678eac3f66a3137b93",
          index: 5,
          depType: "code"
        }
      ]
    - name: "TimeLock"
      codeHash: "0x6fac4b2e89360a1e692efcddcb3a28656d8446549fb83da6d896db8b714f4451"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0x1b4ffcad55ecd36ffb2715b6816b83da73851f1a24fe594f263c4f34dad90792",
          index: 1,
          depType: "code"
        }
      ]
  typeScripts:
    - name: "Nervos Dao"
      codeHash: "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f",
          index: 2,
          depType: "code"
        }
      ]
      scriptHash: "0xcc77c4deac05d68ab5b26828f0bf4565a8d73113d7bb7e92b8362b8a74e58e58"
      typeScriptId: 46
    - name: "TypeId"
      codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944"
      hashType: "type"
      cellDeps: [ ]
    - name: "xUDT(final_rls)"
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xbf6fb538763efec2a70a6a3dcb7242787087e1030c4e7d86585bc63a9d337f5f",
          index: 0,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae"
          }
        }
      ]
      scriptHash: "0x2fa1efd0a1763de4d9f6176ce78dad05476ff6c9a56aec3a0c4e1426d887edac"
      typeScriptId:
    - name: "USDI"
      codeHash: "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xaec423c2af7fe844b476333190096b10fc5726e6d9ac58a9b71f71ffac204fee",
          index: 0,
          depType: "code",
        }
      ]
      symbol: "USDI"
      decimal: 6
      scriptHash: "0x07ac97b5ff3df4b49f59a59f4d80d33d22c1263a57467c512c93b9c29b7a0de3"
      udt: true
      udtType: 15
      typeScriptId:
    - name: "RUSD"
      codeHash: "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a"
      hashType: "type"
      symbol: "RUSD"
      decimal: 8
      scriptHash: "0x45b32a2bc4285d0a09678eb11960ddc8707bc2779887a09d482e9bfe9a2cdf52"
      udt: true
      udtType: 15
      typeScriptId:
    - name: "tBtc"
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb"
      hashType: "type"
      args: "0xe338fcbe878c4c656ac91b296882df9edc8b56cf00ae16acb4f0f49c09bccd02"
      symbol: "tBtc"
      decimal: 8
      udt: true
      udtType: 15
      scriptHash: "0xe6396293287fefb9f26d98eb0318fe80890908f0849226ad0c8cab2d62f1e351"
      typeScriptId:
    - name: "BTCPP"
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb"
      hashType: "type"
      args: "0x6d0cc2e3a8059f36dbee473e14b2b05d19a4d69f5bfd2a7abdc71fd32eece546"
      symbol: "BTCPP"
      decimal: 8
      scriptHash: "0xcc14aba04f0b03a5df5ef2cc2a163ff34c35863fbd65cd137aede0fb40346f66"
      udt: true
      udtType: 15
      typeScriptId:
    - name: "web5did"
      codeHash: "0x510150477b10d6ab551a509b71265f3164e9fd4137fcb5a4322f49f03092c7c5"
      hashType: "type"
    - name: "COTA"
      codeHash: "0x89cd8003a0eaf8e65e0c31525b7d1d5c1becefd2ea75bb4cff87810ae37764d8"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0x636a786001f87cb615acfcf408be0f9a1f077001f0bbc75ca54eadfe7e221713",
          index: 0,
          depType: "depGroup"
        }
      ]
    - name: "Unique Cell"
      codeHash: "0x8e341bcfec6393dcd41e635733ff2dca00a6af546949f70c57a706c0f344df8b"
      hashType: "type"
      cellDeps: [
        {
          txHash: "0xff91b063c78ed06f10a1ed436122bd7d671f9a72ef5f5fa28d05252c17cf4cef",
          index: 0,
          depType: "code",
          type: {
            codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944",
            hashType: "type",
            args: "0xe04976b67600fd25ac50305f77b33aee2c12e3c18e63ece9119e5b32117884b5"
          }
        }
      ]
    - name: "EasyToDiscoverType"
      codeHash: "0xaba4430cc7110d699007095430a1faa72973edf2322ddbfd4d1d219cacf237af"
      hashType: "data1"
      cellDeps: [
        {
          txHash: "0x1b4ffcad55ecd36ffb2715b6816b83da73851f1a24fe594f263c4f34dad90792",
          index: 0,
          depType: "code"
        }
      ]
    - name: ""
      codeHash: "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4"
      hashType: "type"
      args: "0x6fe3733cd9df22d05b8a70f7b505d0fb67fb58fb88693217135ff5079713e902"
      scriptHash: "0x788c79191970e313693351531930b46a708b1ca58f6d414ddc8a8827afb554ff"
      udt: true
      udtType: 3
      typeScriptId: 5530
    - name: ""
      codeHash: "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4"
      hashType: "type"
      args: "0x17d4dd69794ba8074ab69718ab569a98ad89ab806f4b2ad95ef760595235ade6"
      scriptHash: "0xc6c3add6d90a3d1eab9ec478bfa0647012989fb7ccf4a01b9dc0ed0910585a2b"
      udt: true
      udtType: 3
      typeScriptId: 8881
    - name: ""
      codeHash: "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4"
      hashType: "type"
      args: "0x8462b20277bcbaa30d821790b852fb322d55c2b12e750ea91ad7059bc98dda4b"
      scriptHash: "0x5e4229de7f1a6304099385638e4ef3e85ab7a02b0ed4d4a95783ebd982edb691"
      udt: true
      udtType: 3
      typeScriptId: 8543
    - name: ""
      codeHash: "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4"
      hashType: "type"
      args: "0x9c3da505eac9e15cb7986c064728a130e75ab746416be0debf593e9e54f19464"
      scriptHash: "0xdbfd8e50c62549e24ced774e012b1ea34559ee5e1676fddc63ebd7e3618b3e2c"
      udt: true
      udtType: 3
      typeScriptId: 8590
    - name: ""
      codeHash: "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4"
      hashType: "type"
      udt: true
      udtType: 3
remote:
  worker:
    url: http://localhost:8082