spring:
  application:
    name: ckb-explorer-web
  threads:
    virtual:
      enabled: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: rivtower
#    password: rivtower
#    virtual-host: /
  datasource:
#    url: jdbc:postgresql://192.168.160.20:5432/ckb-rich-indexer
    url: jdbc:postgresql://127.0.0.1:15432/explorer
    username: ckb
    password: nervos
    #password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      #host: localhost
      host: 127.0.0.1
      #port: 6379
      port: 16379
      database: 4
        # lettuce:
        #   pool:
          # 虚拟线程下建议关闭连接池（每个请求短平快）
          #     max-active: 200
      #password: abcdefg
      redisson:
        config: |
          singleServerConfig:
            #address: redis://localhost:6379
            #password: abcdefg
            address: redis://127.0.0.1:16379
            database: 4
            idleConnectionTimeout: 10000
            connectTimeout: 10000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
            subscriptionsPerConnection: 5
            clientName: ckb-explorer-web
            # 降低连接池
            connectionMinimumIdleSize: 4
            connectionPoolSize: 16
            dnsMonitoringInterval: 5000
            codec: !<org.redisson.codec.JsonJacksonCodec> {}
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog.yml
    database-change-log-lock-table: liquibase-lock
    database-change-log-table: liquibase-changelog
logging:
  level:
    com.ckb.explorer.mapper: DEBUG
    org.springframework: DEBUG
    com.baomidou: DEBUG
ckb:
  nodeUrl: https://testnet.ckb.dev
  netWork: 2 # 1:mainnet 2:testnet
  default-hash-prefix: 0x
  default-with-prefix-hash-length: 66
statistic:
  averageBlockTimeInterval: 100
  hashRateStatisticalInterval: 100
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
script:
  lockScripts:
    - name: "Secp256k1Blake160"
      codeHash: "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
      hashType: "type"
    - name: "NervosDao"
      codeHash: "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e"
      hashType: "type"
    - name: "Secp256k1Multisig"
      codeHash: "0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8"
      hashType: "type"
    - name: "Secp256k1MultisigV2"
      codeHash: "0x36c971b8d41fbd94aabca77dc75e826729ac98447b46f91e00796155dddb0d29"
      hashType: "data1"
    - name: "iCKB lock"
      codeHash: "0x2a8100ab5990fa055ab1b50891702e1e895c7bd1df6322cd725c1a6115873bd3"
      hashType: "data1"
    - name: "AnyoneCanPay"
      codeHash: "0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356"
      hashType: "type"
    - name: "CHEQUE"
      codeHash: "0x60d5f39efce409c587cb9ea359cefdead650ca128f0bd9cb3855348f98c70d5b"
      hashType: "type"
    - name: "JoyId"
      codeHash: "0xd23761b364210735c19c60561d213fb3beae2fd6172743719eff6920e020baac"
      hashType: "type"
    - name: "OmniLock V2"
      codeHash: "0xf329effd1c475a2978453c8600e1eaf0bc2087ee093c3ee64cc96ec6847752cb"
      hashType: "type"
    - name: "OmniLock V1"
      codeHash: "0x79f90bb5e892d80dd213439eeab551120eb417678824f282b4ffb5f21bad2e1e"
      hashType: "type"
    - name: "PWLock"
      codeHash: "0x58c5f491aba6d61678b7cf7edf4910b1f5e00ec0cde2f42e0abb4fd9aff25a63"
      hashType: "type"
    - name: "NostrLock"
      codeHash: "0x6ae5ee0cb887b2df5a9a18137315b9bdc55be8d52637b2de0624092d5f0c91d5"
      hashType: "type"
    - name: "RgbppLock"
      codeHash: "0x61ca7a4796a4eb19ca4f0d065cb9b10ddcf002f10f7cbb810c706cb6bb5c3248"
      hashType: "type"
    - name: "BtcTimeLock"
      codeHash: "0x00cdf8fab0f8ac638758ebf5ea5e4052b1d71e8a77b9f43139718621f6849326"
      hashType: "type"